"""initial schema

Revision ID: 51105e039d9d
Revises: 
Create Date: 2026-02-09 03:17:51.932942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51105e039d9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_by', sa.String(length=100), nullable=True),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('nbk', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('function_name', sa.String(length=100), nullable=True),
    sa.Column('pm_ic', sa.String(length=10), nullable=True),
    sa.Column('manager_name', sa.String(length=100), nullable=True),
    sa.Column('dl_name', sa.String(length=100), nullable=True),
    sa.Column('dh_name', sa.String(length=100), nullable=True),
    sa.Column('gdl_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('nbk')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('resource_url_1', sa.String(length=255), nullable=True),
    sa.Column('resource_url_2', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_nbk', sa.String(length=20), nullable=False),
    sa.Column('given_by', sa.String(length=100), nullable=True),
    sa.Column('feedback_type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_nbk'], ['employees.nbk'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_nbk', sa.String(length=20), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=True),
    sa.Column('skill_type', sa.String(length=50), nullable=True),
    sa.Column('emp_skill_category', sa.String(length=50), nullable=True),
    sa.Column('user_proficiency', sa.String(length=50), nullable=True),
    sa.Column('expected_current_prof', sa.String(length=50), nullable=True),
    sa.Column('gap_current', sa.String(length=20), nullable=True),
    sa.Column('expected_future_prof', sa.String(length=50), nullable=True),
    sa.Column('gap_future', sa.String(length=20), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_nbk'], ['employees.nbk'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_nbk', sa.String(length=20), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assigned_by', sa.String(length=100), nullable=True),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.Column('target_proficiency', sa.String(length=50), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_nbk'], ['employees.nbk'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_plan_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('target_level', sa.String(length=50), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('milestones')
    op.drop_table('training_plans')
    op.drop_table('skills')
    op.drop_table('feedbacks')
    op.drop_table('training_resources')
    op.drop_table('settings')
    op.drop_table('employees')
    op.drop_table('data_import_logs')
    # ### end Alembic commands ###
